services:
  mt5:
    build:
      dockerfile: Dockerfile
    container_name: mt5
    volumes:
      - mt5_config:/config
    
    environment:
      - CUSTOM_USER=${MT5_USER:-user}
      - PASSWORD=${MT5_PASSWORD:-pass}
      - VNC_DOMAIN=${MT5_VNC_DOMAIN:-localhost}
    networks:
      - dokploy-network
    labels:
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true

volumes:
  mt5_config:
    driver: local