services:
  mt5:
    build:
      context: .
      dockerfile: mt5/Dockerfile
      network: host
    environment:
      - ACCOUNT=
      - PASSWORD=
      - SERVER=
    deploy:
      replicas: 1
    # volumes:
    #   - ./docker/mt5/:/root/.wine/drive_c/fx
    networks:
      - dokploy-network
    labels:
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true

volumes:
  mt5_config:
    driver: local