services:
  mt5:
    build: .
    image: gmag11/metatrader5_vnc
    container_name: mt5
    volumes:
      - mt5_config:/config
    environment:
      - CUSTOM_USER=${MT5_USER:-user}
      - PASSWORD=${MT5_PASS:-password}
    networks:
      - dokploy-network
    labels:
      - "traefik.docker.network=dokploy-network"

networks:
  dokploy-network:
    external: true

volumes:
  mt5_config:
    driver: local